#!/usr/bin/env bash
# After the TRAIN corpus finishes: generate the VAL corpus, audit both, then
# build the augmented CM dataset.
#
# The val corpus is generated by Mistral-Large-3-675B, which is never used to
# generate training data and is not the judge either. That separation is the
# whole point of having it: a CM can score well by learning one generator's
# stylistic tics, and an in-distribution eval would not catch that. Val measures
# whether the CM learned the POLICY or just the phrasing.
#
# The build is fail-closed on coverage (strict_cm_coverage), so a source prompt
# with too few accepted pairs stops the build rather than silently producing a
# thinner dataset than intended.
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

TRAIN_OUT=datasets/augment/cm_pairs_train_batched_20260829.jsonl
VAL_OUT=datasets/augment/cm_pairs_val_batched_20260829.jsonl

# Wait for the train generator to exit. Bracketed pattern so this script's own
# command line cannot match the pgrep (that self-match killed a monitor earlier).
while pgrep -f 'gen[_]pairs[_]batched.*role train' >/dev/null 2>&1; do
  sleep 120
done
echo "$(date -Is) train corpus finished: $(wc -l < "$TRAIN_OUT") records"

set -a; . /home/ubuntu/.nchc_env; set +a

echo "$(date -Is) generating VAL corpus (held-out generator)"
python3 -m scripts.augment.gen_pairs_batched --role val \
  --prompts datasets/augment/prompts_val.jsonl \
  --out "$VAL_OUT" \
  --pairs-per-prompt 5 --api-interval-seconds 3 --workers 3 \
  >> logs/cm_pairs_batched_val_20260829.log 2>&1
echo "$(date -Is) val corpus: $(wc -l < "$VAL_OUT") records"

echo "$(date -Is) auditing"
python3 scripts/augment/audit_cm_pairs.py --train "$TRAIN_OUT" --val "$VAL_OUT" \
  > results/cm_pairs_audit_20260829.json 2>&1 || echo "audit reported issues (see file)"
cat results/cm_pairs_audit_20260829.json 2>/dev/null | head -20

echo "$(date -Is) building augmented CM dataset"
python3 scripts/augment/build_cm_dataset.py \
  --base-train datasets/cost/splits/by_prompt_seed42/train.jsonl \
  --base-eval datasets/cost/splits/by_prompt_seed42/eval.jsonl \
  --pairs-train "$TRAIN_OUT" \
  --pairs-val "$VAL_OUT" \
  --out-dir datasets/cost/cm_augmented_20260829 \
  --min-accepted-per-prompt 3
echo "$(date -Is) build complete"
ls -la datasets/cost/cm_augmented_20260829/ 2>/dev/null
